[versions]
junit-jupiter = "6.0.1"
lombok = "1.18.42"
vavr = "1.0.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }
